name: ecommerce
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"
  # ..........................Packages.....................#

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  iconsax: ^0.0.8

# State managment

  get: ^4.6.6

  
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  # ..............Local assets..............#

  assets:
    - assets/images/ 
    - assets/icons/
    - assets/logos/

  # Local fonts

  fonts:
    - family: Schyler
      fonts:
        - asset: fonts/Schyler-Regular.ttf
        - asset: fonts/Schyler-Italic.ttf
          style: italic
    - family: Trajan Pro
      fonts:
        - asset: fonts/TrajanPro.ttf
        - asset: fonts/TrajanPro_Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - assets:fonts/Poppins-Bold.ttf